language: python
cache: packages
install:
- ./.testing/install-ci.sh
# Create working directory
- mkdir test
- cp reference-data/SCA8_region.bed test/
- cd test/
# command to run tests
script:
# Run the test data
- ../tools/bin/bpipe run ../pipelines/STRetch_exome_pipeline.groovy ../test-data/*.fastq.gz
- if diff STRs.tsv ../.testing/STRs.benchmark.tsv; then echo exit 0; else echo exit 1; fi
after_script:
- head *.locus_counts *.STR_counts *.median_cov
- head *.tsv
